#!/bin/bash

which installfromuri > /dev/null
installfromuri_available=$?

which addvhost > /dev/null
addvhost_available=$?

which downloadwordpress > /dev/null
downloadwordpress_available=$?

which ask_mysql > /dev/null
ask_mysql_available=$?


##
# Do stuffs.
# Suppose that all utilities needed already is in the system
#
installwordpress_dostuffs() {

    if [ -z $1 ]; then
        echo You need to provides two arguments:
        echo first: The site name
        echo second: The path for the local virtualhost folder
    fi

    downloadwordpress $1

    source $(which addvhost)

    addvhost_dostuffs $1

    ##
    # The $htdocs_root comes from the addvhost
    #
    mv $1 $htdocs_root/

    source $(which ask_mysql)
    do_ask_mysql
}

##
# Tries to download the things
#
installwordpress_donwloadeverything() {
    echo Something is missing...
}

##
# Everything needed is here?
#
if [ $addvhost_available -eq 0 ] && [ $downloadwordpress_available -eq 0 ] ; then
    installwordpress_dostuffs $1
else
    installwordpress_donwloadeverything
fi
