#!/bin/bash

which installfromuri > /dev/null
installfromuri_available=$?

which addvhost > /dev/null
addvhost_available=$?

which downloadwordpress > /dev/null
downloadwordpress_available=$?

##
# Debug
# please, remove after the development is finished
#
echo installfromuri: $installfromuri_available
echo addvhost: $addvhost_available
echo downloadwordpress: $downloadwordpress_available

##
# Do stuffs.
# Suppose that all utilities needed already is in the system
#
installwordpress_dostuffs() {

    if [ -z $1 ]; then
        echo You need to provides two arguments:
        echo first: The site name
        echo second: The path for the local virtualhost folder
    fi

    downloadwordpress $1
    ls
    # mv $1 $2
    #source $(which addvhost) $1
    echo Aloha!!!!
}

##
# Tries to download the things
#
installwordpress_donwloadeverything() {
    echo Something is missing...
}

##
# Everything needed is here?
#
if [ $addvhost_available -eq 0 ] && [ $downloadwordpress_available -eq 0 ] ; then
    installwordpress_dostuffs
else
    installwordpress_donwloadeverything
fi
